baseURL = "https://joeykaan.nl"
languageCode = "en-us"
title = "Joey Kaan"
author = "Joey"
copyright = "Joey"
googleanalytics = "UA-48594289-4"
theme = "hugo-coder"
disqusShortname = "joeykaan"
paginate = 20
canonifyurls = true
pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    keywords = "blog,developer,personal"
    avatarurl = "/profile.jpeg"
    hidecredits = true
    hidecopyright = true
    math = true

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jkaan/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 1
    url = "https://twitter.com/joeykaan/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 1
    url = "https://medium.com/@joeykaan"
